/**
 * 
 */
package util.exception;

/**
 * @author nihil
 *
 */
public enum ExceptionType {
    ACTION,
    NOT_REACHABLE,
    TOO_MANY_CARD,
    INADEQUATE_USE_OF_CAPACITY,
    TILE_STATE,
    PLAYER_OUT_OF_ISLAND,
    END_GAME_VICTORY,
    END_GAME_TREASURE,
    END_GAME_DEATH,
    END_GAME_WATER,
    END_GAME_HELI,
    END_GAME,
    NOT_ENOUGH_CARD,
    WRONG_TILE_TREASURE,
    MISSING_CARD,
    INCORRECT_TILE,
    DIFFERENT_TILE,
    NAVIGATOR_CANNOT_MOVE_HIMSELF,
    PLAYER_NOT_IN_SAME_TILE;
}
